### ISSUE TITLE
Switch from spi to pi-spi 

### ISSUE THREAD

**Issue by kentandersen** [fiskeben/mcp3008.js#3]
[node-spi](https://github.com/RussTheAerialist/node-spi) (used to communicate with the spi interface) does not support node version beyond 0.12.x. [According to the developer](https://github.com/RussTheAerialist/node-spi/issues/21) node-spi is abandon, and will not be updated to support node 4 or 5. He pointed me to [pi-spi](https://github.com/natevw/pi-spi) which is still alive. 

Could you change the dependency from spi to pi-spi, in order to make it work on recent versions of node? :smile:

**Comment by kennethdammyr** [comment]
Plus one!

**Comment by fiskeben** [comment]
I'll look into it :)
