### ISSUE TITLE
Software SPI

### ISSUE THREAD

**Issue by AshMartian** [fiskeben/mcp3008.js#5]
I am away from my Pi at the moment, but could this be used with Software SPI? (hardware SPI being used for touchscreen).

I found this module, it seems like it could be a drop-in replacement or a configuration parameter.

https://www.npmjs.com/package/rpi-softspi

**Comment by fiskeben** [comment]
Sorry for not getting back to you sooner.

I'm not familiar with software SPI so I really can't answer that. I'd love to know more about it if you care to come up with an example.

**Comment by AshMartian** [comment]
No worries! I haven’t reached the point of needing it. When I do, I’ll see if I can find an implementation and make a pull request if I do if that is okay :)
